# Generated by Django 4.2.6 on 2023-10-20 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20220225_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedcustomerappointment',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EngineerApprovedApp', to='appointments.engineer'),
        ),
    ]
