# Generated by Django 4.2.6 on 2023-10-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_information', models.CharField(max_length=100)),
                ('tier', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('experience', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Electrician', 'Electrician'), ('Plumber', 'Plumber')], default='Electrician', max_length=50),
        ),
    ]
