# Generated by Django 4.2.6 on 2023-10-20 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_staff_alter_appointment_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='contact_information',
            new_name='contact_number',
        ),
    ]
