# Generated by Django 4.2.6 on 2023-10-31 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_appointment_address_alter_appointment_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='contact_number',
            field=models.CharField(default='No', max_length=15),
        ),
    ]
