# Generated by Django 4.2.6 on 2023-10-31 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_appointment_contact_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='contact_number',
            new_name='isFinished',
        ),
    ]
