# Generated by Django 4.2.6 on 2023-10-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_staff_tier_vendorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='staff',
            field=models.CharField(default='Not assigned', max_length=50),
        ),
    ]
