# Generated by Django 4.2.6 on 2023-10-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_appointment_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time_ordered',
        ),
    ]
