# Generated by Django 4.2.6 on 2023-10-31 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_rename_contact_number_appointment_isfinished'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='isFinished',
            field=models.CharField(default='No', max_length=15),
        ),
    ]
