# Generated by Django 4.2.6 on 2023-10-31 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_inquiry_isfinished'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
