# Generated by Django 4.2.6 on 2023-10-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_appointment_day_alter_staff_tier_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='assigned_user',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='inquiry_message',
            field=models.TextField(default=''),
        ),
    ]
