# Generated by Django 4.2.6 on 2023-10-26 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_staff_assigned_user_staff_inquiry_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='staff',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
