# Generated by Django 4.2.6 on 2023-11-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_inquiry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.CharField(choices=[('2023-11-03', '2023-11-03'), ('2023-11-04', '2023-11-04'), ('2023-11-05', '2023-11-05'), ('2023-11-06', '2023-11-06'), ('2023-11-07', '2023-11-07'), ('2023-11-08', '2023-11-08'), ('2023-11-09', '2023-11-09')], default='Monday', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(blank=True, choices=[('9 am', ' 10 am '), ('10 am', ' 11 am ')], default='3 PM', max_length=10, null=True),
        ),
    ]
