# Generated by Django 4.2.6 on 2023-11-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_appointment_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='staff',
            field=models.CharField(default='Not assigned', max_length=50),
        ),
    ]
