# Generated by Django 4.2.6 on 2023-10-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
        migrations.DeleteModel(
            name='Tier',
        ),
    ]
